server:
  port: 8008
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8


spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  #配置 Jpa
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: true

#配置rocketmq
#rocketmq:
#  nameServer: localhost:9876
#  producer:
#    group: yshop-group
#    sendMessageTimeout: 300000



#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
#  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  level:
    co.yixiang: DEBUG
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG





yshop:
  #相关配置
  version: 3.1

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns:

jwt:
  header: Authorization
    # 令牌前缀
  token-start-with: Bearer
  online-key: yshopapp


# sm.ms 图床的 token
smms:
  token: 1oOP3ykFDI0K6ifmtvU7c8Y1eTWZSlyl
